### ISSUE TITLE
can't correction the text, is it my error?

### ISSUE THREAD

**Issue by jinkangfly** [bminixhofer/nlprule#10]
from nlprule import Tokenizer, Rules, SplitOn

tokenizer = Tokenizer.load("en")
rules = Rules.load("en", tokenizer, SplitOn([".", "?", "!"]))

rules.correct("He want that you send him a email.")
# returns: He want you to send him a email.

**Comment by bminixhofer** [comment]
This looks right to me. Is there something I'm missing? it corrects "He want **that you** send him a email." to "He want **you to** send him a email.")

```python
(base) bminixhofer@pop-os:~$ ipython
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from nlprule import Tokenizer, Rules, SplitOn
   ...: 
   ...: tokenizer = Tokenizer.load("en")
   ...: rules = Rules.load("en", tokenizer, SplitOn([".", "?", "!"]))
   ...: 
   ...: rules.correct("He want that you send him a email.")
Out[1]: 'He want you to send him a email.'
```

**Comment by bminixhofer** [comment]
It doesn't capture the errors "want that" (should be "wants that") and "a email" (should be "an email") but it does find all grammatical errors, only ones for which there are rules.
