### ISSUE TITLE
Tighter error bounds around `Error`

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#33]
In https://github.com/bminixhofer/nlprule/blob/main/build/src/lib.rs#L23 the bounds are `Box<dyn std::error::Error>` where it should be `Box<dyn std::error::Error + Send + Sync + 'static>` for maximum compatibility with error frameworks.

**Comment by drahnr** [comment]
Note that in this particular case, one could also consider making the error a generic with the above bounds.

The impact is low anyways, it's all in the `nlprule-build` crate where error handling is commonly equiv to `panic!()`

**Comment by bminixhofer** [comment]
Thanks for the issue. I think a generic is best. 

And yes, at the moment it panics most of the time. I could fix this while I'm at it too so it can potentially be used outside `build.rs`.
