### ISSUE TITLE
postprocess has different semantic than anticipated

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#34]
So for my usecase as defined in #27 is reversed.

`nlprule-data/0.4.4/en/en_tokenizer.bin`
`target/debug/build/cargo-spellcheck-2b832a17a2fec7ef/out/en_tokenizer.bin.brotli`

What the usecase described in #27 would require, is to be able to apply compression before storing it in the cache dir and then uncompressing it for the `target/debug/...`.

Reasoning: When uploading with cargo it picks a subset of the git tree, the size of the binary is not relevant.

I think adding a secondary `fn cache_preprocess()` so I can compress it there before it is stored to `$cache_dir` and then decompress as part of the current `fn postprocess()` so it ends up only as `binenc`oded in the `$OUT_DIR` from where it can be included in the binary.

**Comment by bminixhofer** [comment]
Oh sorry, I misunderstood the original issue then. In any case a `postprocess` function makes sense to reduce the size of the final binary.

Your proposed `cache_preprocess` function also makes sense. I have to think a bit about the naming, that function would basically transform the buffer to some other buffer immediately after downloading it.

I'm not quite happy with that additional complexity and with having to store the binaries in-tree as you do in `cargo-spellcheck` now but I don't think there's a better solution..

**Comment by bminixhofer** [comment]
Actually you don't have to store the binaries in-tree if you just run the `build.rs` once before `cargo publish`, right? In that case only the additional complexity is an issue and that's not too bad in the `nlprule-build` crate.

**Comment by drahnr** [comment]
I don't think this works. Cargo requires all sources to be able to rebuild, and that's part of the "deploy when github is down" user story.

**Comment by drahnr** [comment]
I'd be happy to create PR if you are willing to accept it.

**Comment by bminixhofer** [comment]
That would be great, sure! I think the best solution is a `transform` function which transforms the binary immediately after downloading / building. It has to be transformed consistently regardless of whether it is built from the build directory or downloaded.

My comment above was perhaps a bit confusing because I conflated the two things (this issue and storing the binaries in-tree), what I meant was that you can just

```
cargo build # <- creates the nlprule-data directory in your case
cargo publish --allow-dirty
```

if you didn't want to store the binaries in Git.

**Comment by drahnr** [comment]
> That would be great, sure! I think the best solution is a `transform` function which transforms the binary immediately after downloading / building. It has to be transformed consistently regardless of whether it is built from the build directory or downloaded.
> 
> My comment above was perhaps a bit confusing because I conflated the two things (this issue and storing the binaries in-tree), what I meant was that you can just
> 
> ```
> cargo build # <- creates the nlprule-data directory in your case
> cargo publish --allow-dirty
> ```

That would work, but it includes the risk of publishing a local state of uncommitted changes which I am not keen on. It seems to be a solution, but not a pretty one.

> if you didn't want to store the binaries in Git.

I do :) the user story should not differ between crates-io and a git checkout.

**Comment by bminixhofer** [comment]
> one can also install directly from git with cargo

Oh, that's a good point then. I just thought it's not ideal because it might blow up the size of the repository a bit.
