### ISSUE TITLE
Loading rules error: invalid value: integer 7, expected variant index 0 <= i < 2

### ISSUE THREAD

**Issue by Qeenon** [bminixhofer/nlprule#49]
I've generated rules.bin for English (same way as it was used in CI)

And when I'm trying to do Rules::new I'm getting this error: `invalid value: integer 7, expected variant index 0 <= i < 2`
I've used to generate on git sources and use on 0.4.6, trying to use on git sources to see if it's versions incompatibility

**Comment by bminixhofer** [comment]
This looks a lot like https://github.com/bminixhofer/nlprule/issues/20. 

> I've used to generate on git sources and use on 0.4.6, trying to use on git sources to see if it's versions incompatibility

At the moment there is zero compatibility between versions so you have to use the exact same version of the library for generating the binaries as for loading them. If you're using a release of nlprule you can just download the correct binaries from GH releases: https://github.com/bminixhofer/nlprule/releases/tag/0.4.6

**Comment by Qeenon** [comment]
yes, loading rules under same commit version helps

**Comment by bminixhofer** [comment]
Great! The error message is really bad at the moment, will be solved by #20 :)
