### ISSUE TITLE
panic in `Regex::regex()`

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/nlprule#68]
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/build/56ca5ece/git-pull-request-resource/../cargo/registry/src/github.com-1ecc6299db9ec823/nlprule-0.6.2/src/utils/regex.rs:78:33

thread 'stack backtrace:

<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /tmp/build/56ca5ece/git-pull-request-resource/../cargo/registry/src/github.com-1ecc6299db9ec823/nlprule-0.6.2/src/utils/regex.rs:78:33

   0:     0x560ee78bdfd0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e

                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5

   1:     0x560ee78bdfd0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9

                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
```

There is an `.unwrap` on the `regex.borrow()` call which panics.

https://ci.spearow.io/teams/main/pipelines/cargo-spellcheck/jobs/pr-validate/builds/45

**Comment by drahnr** [comment]
A bit of context:

`Rules::suggest(...)` is called in parallel over a shard immutable reference to a single `&Rules` instance. So this might be an issue with `lazycell`'s atomic ordering semantics.

**Comment by bminixhofer** [comment]
Hi, thanks for the issue. Refreshingly, something which I couldn't have foreseen :)

I believe the easiest fix is just to replace `lazycell` with `once_cell`, which is a more well used dependency anyway and has the `get_or_init` API which fits our use case. 

I went ahead and implemented this: #69. Can you check if this solves the problem? Binaries from the latest release should still work.

**Comment by drahnr** [comment]
Just had a peek into the `once_cell` crate, and there is a significant amount of non trivial synchronization logic happening, but I ran it a few times and it works consistently :tada: - so #69 is good to go :)

**Comment by drahnr** [comment]
Could you craft a release, that's the last thing pending for a cargo-spellcheck 0.8.0 which is again needed for  https://github.com/paritytech/parity-bridges-common/pull/832

**Comment by bminixhofer** [comment]
Sure! Release CI is running for 0.6.3 now.
