### ISSUE TITLE
Compile error in build.rs from README.md

### ISSUE THREAD

**Issue by shybyte** [bminixhofer/nlprule#73]
Using nlprule and nlprule-build version 0.6.4 and the build.rs script from the current README.md,  I get a compile error while building:

```
error[E0599]: no method named `validate` found for enum `Result<BinaryBuilder, nlprule_build::Error>` in the current scope
 --> build.rs:9:6
  |
9 |     .validate();
  |      ^^^^^^^^ method not found in `Result<BinaryBuilder, nlprule_build::Error>`
```

I have solved it by adding error propagation to builds.rs:
```rust
fn main() -> Result<(), nlprule_build::Error> {
    println!("cargo:rerun-if-changed=build.rs");
    nlprule_build::BinaryBuilder::new(
        &["en"],
        std::env::var("OUT_DIR").expect("OUT_DIR is set when build.rs is running"),
    )
    .build()?
    .validate()
}
```
If you want, I can make a PR.

**Comment by bminixhofer** [comment]
Hi, thanks, good catch!

I'm hoping to remove some of this complexity soon (#72) which will make it easier to use.

Sure, a PR would be great. But if it's not convenient for you I can fix this myself later today.

**Comment by shybyte** [comment]
Probably it would be easier for you to just fix this problem yourself, but I'm keen to contribute to your cool project.  :smiley:

**Comment by bminixhofer** [comment]
It would've probably taken roughly the same time, and there's certainly some symbolic value :) Thanks for contributing!
