### ISSUE TITLE
Downloading from Github Releases sometimes times out

### ISSUE THREAD

**Issue by micky-git** [bminixhofer/nlprule#9]
tokenizer = Tokenizer.load("en")

ValueError: error decoding response body: operation timed out

**Comment by bminixhofer** [comment]
That's an issue with file hosting via Github Releases. You're the second person to report this, I might check if it's possible to host the files elsewhere. 
In the meantime, the workaround mentioned in https://github.com/bminixhofer/nlprule/issues/6#issuecomment-757108636 works. Download the files manually from [https://github.com/bminixhofer/nlprule/releases] and load them with:
```python
tokenizer = Tokenizer("path/to/en_tokenizer.bin")
```

**Comment by micky-git** [comment]
gunzipping failed: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }

**Comment by bminixhofer** [comment]
Can you paste your code?

**Comment by micky-git** [comment]
version info:
platform:windows64 & mac bigsur
rustc 1.49.0 (e1884a8e3 2020-12-29)
Python 3.7.6
conda 4.9.2
nlprule 0.3.0
tokenizer:https://github.com/bminixhofer/nlprule/releases/download/0.3.0/en_tokenizer.bin.gz
IDE Spyder



code here(python3.7):

>\# -*- coding: utf-8 -*-
>"""
>Created on Tue Jan 19 18:41:01 2021
>\@author: A
>"""
>from nlprule import Tokenizer, Rules, SplitOn
>tokenizer = Tokenizer.load("en_tokenizer.bin")
>rules = Rules.load("en", tokenizer, SplitOn([".", "?", "!"]))
>rules.correct("He wants that you send him an email.")
>rules.correct("Thanks for your’s and Lucy’s help.")
>rules.correct("I can due his homework.")
>suggestions = rules.suggest("She was not been here since Monday.")
>for s in suggestions:
>print(s.start, s.end, s.text, s.source, s.message)


output here:
>runfile('D:/ai/test/helloworld/test.py', wdir='D:/ai/test/helloworld')
>Traceback (most recent call last):
>
>  File "D:\ai\test\helloworld\test.py", line 8, in <module>
>    tokenizer = Tokenizer.load("en_tokenizer.bin")
>
>PanicException: gunzipping failed: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }`

**Comment by micky-git** [comment]
btw:unzip with bandizip(windows_64):http://www.bandisoft.com/

**Comment by micky-git** [comment]
I tried:
tokenizer = Tokenizer.load("en_tokenizer.bin")#copy en_tokenizer.bin to workpath
tokenizer = Tokenizer.load("en_tokenizer.bin")#copy en_tokenizer.bin to package_nlprule_path

tokenizer = Tokenizer.load("D:\ai\test\helloworld\en_tokenizer.bin")
tokenizer = Tokenizer.load("D:\\ai\\test\\helloworld\\en_tokenizer.bin")
tokenizer = Tokenizer.load("D:/ai/test/helloworld/en_tokenizer.bin")

tokenizer = Tokenizer.load(r"D:\ai\test\helloworld\en_tokenizer.bin")
tokenizer = Tokenizer.load(r"D:\\ai\\test\\helloworld\\en_tokenizer.bin")
tokenizer = Tokenizer.load(r"D:\\ai\\test\\helloworld\\en_tokenizer.bin")

tokenizer = Tokenizer.load(f"D:\ai\test\helloworld\en_tokenizer.bin")
tokenizer = Tokenizer.load(f"D:\\ai\\test\\helloworld\\en_tokenizer.bin")
tokenizer = Tokenizer.load(r"D:\\ai\\test\\helloworld\\en_tokenizer.bin")

tokenizer = Tokenizer.load(f"en_tokenizer.bin")
tokenizer = Tokenizer.load("../en_tokenizer.bin")

I'm not quite understand the argument that func_load passes

**Comment by bminixhofer** [comment]
Thanks for the code. So `.load` takes a *language code* e.g "en" or "de" as input and downloads the binary automatically. Since this does not seem to work in your case, you can load it manually with the constructor of the Tokenizer, *not with `.load`*.

This code should work:

```python
tokenizer = Tokenizer("en_tokenizer.bin") # no .load, just Tokenizer(..)!
```

**Comment by bminixhofer** [comment]
The binaries are now significantly smaller so I hope this won't happen anymore. I'm closing this for now, please comment / reopen if there's anymore issues with timeouts.
